package ru.skypro.avito.exception;

public class BadCredentialsException extends RuntimeException {
    public BadCredentialsException(String user_not_found) {

    }
}
